learning_users/basic_app/urls.py
from django.urls import path,include
from basic_app import views

# Template URLS 
app_name = 'basic_app'

urlpatterns = [
   path('register/',views.register ,name='register'),
   path('log_in',views.log_in,name='log_in'),

]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index ,name = 'index'),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.log_out,name='log_out'),
    path('special/',views.special,name='special'),

]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User 
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)

    #additional site
    Website = models.URLField(blank = True)
    
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__ (self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('Website','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm


#Importing for creating a login page

from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password) #setting up the hash.
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user #re-establishing the one - to - one relationship defined in UserProfileInfoForm

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                
                
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form' : user_form,'profile_form' : profile_form,'registered' : registered})



#Creating the login view
def log_in(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        #using Django's builtin authenticate function
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else :
                return HttpResponse('Sorry,your account is not active!')
        else :
            print('Anonymous login request and it failed.')
            print(f'Username : {username} and Password : {password}')
            return HttpResponse('Invalid Login Details')
    else:
        return render(request,'basic_app/login.html')
            

#Using Decorators to Logout of after logging in 
@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse('You are logged in!')
    

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
          </li>
          {% if user.is_authenticated%}
           <li>
            <a href="{% url 'log_out' %}" class="nav-link">Logout</a>
           </li>
           {% else %}
           <li>
            <a href="{% url 'basic_app:log_in' %}" class="nav-link">Login</a>
           </li>

          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
    <div class="container">
        {% block body_block %}
    
        {% endblock %}

    </div>
    
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to Home Page!</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}


{% block body_block %}
<div class="jumbotron">
    <h1>Login Page!</h1>
    <form action="{% url 'basic_app:log_in' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username:">

        <label for="password">Password</label>
        <input type="password" name="password">

        <input type="submit" value="login" class="btn btn-primary">

    </form>
</div>



{% endblock %}





  <!-- <nav class="navbar navbar-default navbar-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a> </li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>

        </ul>
    </div>
</nav> -->

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}

{% load static %}
{% block body_block %}
<div class="jumbotron ">
    {% if registered %}
    <h1>Hurrah! You have successfully registered.</h1>
    {% else %}
    <h1>Enter your details here!</h1>
    <h4>Make sure to fill out all entries.</h4>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p}}
        {{ profile_form.as_p }}
        <input type="submit" value="register" class="btn btn-primary active">
    </form>
    {% endif %}
</div>
{% endblock %}